In [13]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
print(type(a))

<class 'numpy.ndarray'>


In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

## Array Creation

In [11]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [14]:
b = np.array(2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [17]:
c = np.array([(1.5,2,3),
              (4,5,6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

## Basic Operations

In [44]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [45]:
a

array([20, 30, 40, 50])

In [46]:
a.shape

(4,)

In [47]:
b

array([0, 1, 2, 3])

In [48]:
c = a - b
c

array([20, 29, 38, 47])

In [49]:
d = b**2
d

array([0, 1, 4, 9])

In [50]:
e = 10* np.sin(b)
e

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [51]:
# Logical Operations
print(a < 35)

[ True  True False False]


In [52]:
print(a*b)

[  0  30  80 150]


In [53]:
f = a @ b
f

260

## Indexing, Slicing, Iterating

In [62]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [63]:
a[3]

27

In [64]:
g = a[3:11]
g

array([ 27,  64, 125, 216, 343, 512, 729])